### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by janteuni** [meriadec/samus#2]
Hi,

Your project is **Awesome**, I use it every monday to watch my _weekly_ GOT episode,
It would be very usefull to launch samus with a flag to render the video in full screen mode!
I suggest to add a `-f` argument to do this :)

Cheers,

**Comment by meriadec** [comment]
good idea. i'm on it.

**Comment by meriadec** [comment]
This is a thing now, you just have to do:

``` bash
samus -f <url>
```

aaand it will launch in full screen :)
