### ISSUE TITLE
List looping & history select

### ISSUE THREAD

**Issue by balthazar** [meriadec/samus#5]
Hitting the up key while on top should allow us to go at the end of the list. Also, what could be nice is to automatically be selected by default on the last folder item that was watched (disabled for the root folder).

Could be useful for my long collection of public-domain documentaries.

What do you think @meriadec?

**Comment by meriadec** [comment]
I like the process of brainstorming
I like the creativity you put on this.
I give much kudos to that.

Let's take the two points one by one.

1. **_"Hitting the up key while on top should allow us to go at the end of the list"_**
    - I presume that hitting the down key while you are on top should go to the top? Can you confirm?
    - What you propose is modifying the default behaviour of [blessed.list](https://github.com/chjj/blessed#lists), is it correct? I think this _could_ be a thing, tweaking with `select` event and `select` method.. But is it worth it? That's what I'm asking.

2. ***"automatically be selected by default on the last folder item that was watched"***
    - Hmm.
    - The ***"by default"*** hit my heart so much that I started puking at the same second. Couldn't it be an option?
    - What solution are you thinking about for solving this problem, a new file storing the last position of the cursor? Like, `.samuslastposition`? Or, `.samus_Position_of_selectedText-when-last-samus_session.txt`. A better way would be to merge it with `.samus_history`, but we should think of a real encoding for this file (e.g: see `.viminfo`)

Cheers.

**Comment by meriadec** [comment]
ps: if you think I didn't notice that the proposal badge color was taken from monokai color scheme, you failed.

**Comment by balthazar** [comment]
I was going to make a joke by merging my thing in blessed and call you retarded for not seeing the option, but noticed this repo is dead since one fucking year. I'm sad.

"By default" was a bad wording from my part, I'm sorry. I actually wanted to say: "optional by default". As for the solution, I'm more thinking about something just looking at the current list and selecting the last one, don't even know if it's feasible with the code, but yolo. If it would have been in a file, I would certainly have choose to use something like `.s4mus_Positi0n__0f_sel3ctedText-when-last-samus,session.TXT` (More secure and BEM-friendly)

Oh, I absolutely had no idea!
